apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 80

# This makes them available as files in the container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 80
    
    
